baseURL = 'https://travels.toozej.com'
languageCode = 'en-us'
title = 'Travels and Adventures'
theme = 'newsroom'
enableRobotsTXT = true
paginate = 30

[params]
blogDir = "blog"
logo = "" # if the value is an empty string, the site title will be shown instead
faviconsDir = "images/fav/" # with a trailing slash
