baseURL = 'https://travels.toozej.com'
languageCode = 'en-us'
title = 'Travels and Adventures'
theme = ['newsroom', 'gpx-shortcode']
enableRobotsTXT = true
pagination.pagerSize = 30

[taxonomies]
tag = 'tags'
category = 'categories'

[params]
rss = true
blogDir = "blog"
logo = "" # if the value is an empty string, the site title will be shown instead
faviconsDir = "images/fav/" # with a trailing slash
